apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: smarman/guestbook:k8s2
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
